# Generated by Django 5.1.6 on 2025-03-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_experience_remove_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('invisible', 'Invisible'), ('donotdisturb', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
