# Generated by Django 4.2.20 on 2025-03-14 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pong_game', '0002_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('theme_preference', models.CharField(choices=[('fire', 'Fire'), ('water', 'Water')], default='fire', max_length=10)),
                ('difficulty_preference', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchmaking_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
