# Generated by Django 4.2.20 on 2025-03-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0002_remove_game_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=15),
        ),
    ]
