# Generated by Django 5.1.7 on 2025-03-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0003_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
