# Generated by Django 5.1.7 on 2025-03-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0004_playerprofile_experience_playerprofile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
